### ISSUE TITLE
[iPhone]: Scan function has no response

### ISSUE THREAD

**Issue by esburch** [josephrkramer/batuu-scanner#22]
Device: iPhone 13 Pro
iOS: 17.3.1
Browser: Safari and Chrome

After the site loads, I click scan and grant the camera access. When I point the camera at a known QR code (cantina coaster), nothing happens. I wasn't sure if I needed to click Scan specifically, so I also tried that and got nothing. Clicking "Cargo Hold" turns off the camera, but does not show anything either.

**Comment by josephrkramer** [comment]
Possibly related to https://github.com/nimiq/qr-scanner/issues/242

**Comment by josephrkramer** [comment]
Confirmed not working on iPhone

**Comment by josephrkramer** [comment]
Consider switching scanner implementation to https://github.com/mebjas/html5-qrcode

**Comment by josephrkramer** [comment]
Resolved in the rebuilt [batuu-scanner2](https://github.com/josephrkramer/batuu-scanner2)
